name: simulador_de_memoria
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  desktop_window: ^0.4.0
  easy_dynamic_theme: ^2.3.1
  flutter:
    sdk: flutter
  responsive_sizer: ^3.2.0
  sidebarx: ^0.15.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/iconos/
  uses-material-design: true


